# ����˿�
server.port=8208
# ������
spring.application.name=service-statistics
# �������ã�dev��test��prod
spring.profiles.active=dev

# nacos�����ַ
spring.cloud.nacos.discovery.server-addr=127.0.0.1:8848

# RabbitMQ配置
spring.rabbitmq.host=127.0.0.1
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest