# ����˿�
server.port=8205
# ������
spring.application.name=service-oss

#����json��ȫ��ʱ���ʽ
spring.jackson.date-format=yyyy-MM-dd HH:mm:ss
spring.jackson.time-zone=GMT+8


# nacos�����ַ
spring.cloud.nacos.discovery.server-addr=127.0.0.1:8848

# RabbitMQ配置
spring.rabbitmq.host=127.0.0.1
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

aliyun.oss.endpoint=${ALIYUN_OSS_ENDPOINT:oss-cn-beijing.aliyuncs.com}
aliyun.oss.accessKeyId=${ALIYUN_OSS_ACCESS_KEY_ID}
aliyun.oss.secret=${ALIYUN_OSS_ACCESS_KEY_SECRET}
aliyun.oss.bucket=${ALIYUN_OSS_BUCKET}